import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
import { STLLoader } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/STLLoader.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js';
const $=id=>document.getElementById(id),text=$('text'),size=$('size'),width=$('width'),body=$('body'),ink=$('ink'),result=$('result'),notice=$('notice');
for(const [series,colors] of filamentColors){const group=document.createElement('optgroup');group.label=series;for(const [name,hex] of colors){const option=document.createElement('option');option.value=`${series} - ${name}`;option.dataset.hex=hex;option.textContent=`${series} - ${name}`;group.append(option)}body.append(group);ink.append(group.cloneNode(true))}body.value='PLA Matte - Charcoal';ink.value='PLA Matte - Ivory White';
const viewer=$('viewer'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,1,.1,1000),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(viewer.clientWidth,viewer.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;viewer.append(renderer.domElement);camera.position.set(110,-235,185);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(86,80,0);scene.add(new THREE.HemisphereLight(0xffffff,0x173c34,2.8));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(40,-90,210);scene.add(key);const group=new THREE.Group();group.rotation.x=-.28;scene.add(group);const loader=new STLLoader(),material=new THREE.MeshStandardMaterial({color:0x000000,roughness:.46,metalness:.05});let parts=[];const files=['left_end','left_arm','centre_fixed','right_arm','right_end'];Promise.all(files.map(n=>new Promise((resolve,reject)=>loader.load(`assets/${n}.stl`,g=>resolve([n,g]),undefined,reject)))).then(items=>{for(const [name,geometry]of items){geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,material.clone());mesh.name=name;group.add(mesh);parts.push(mesh)}update();}).catch(()=>{$('widthReadout').textContent='3Dデータを読み込めませんでした。'});
function selectedHex(select){return select.options[select.selectedIndex]?.dataset.hex||'#000000'}
function update(){const safe=text.value.slice(0,10)||'YOUR NAME';$('previewText').textContent=safe;$('previewText').style.fontSize=`${Math.min(18,Math.max(9,+size.value||12))}px`;$('previewText').style.color=selectedHex(ink);const d=Math.max(-30,Math.min(30,+width.value||0))/2;$('widthReadout').textContent=d===0?'ドラッグで回転・スクロールで拡大':`標準幅 ${d>0?'+':''}${d*2} mm　ドラッグで回転`;for(const mesh of parts){mesh.material.color.set(selectedHex(body));mesh.position.set(0,0,0);mesh.scale.set(1,1,1);if(mesh.name==='left_arm'){mesh.scale.x=(30+d)/30;mesh.position.x=43-43*mesh.scale.x}else if(mesh.name==='centre_fixed'){mesh.position.x=d}else if(mesh.name==='right_arm'){mesh.scale.x=(30+d)/30;mesh.position.x=d+99-99*mesh.scale.x}else if(mesh.name==='right_end'){mesh.position.x=d*2}}}
[text,size,width,body,ink].forEach(x=>x.addEventListener('input',update));[body,ink].forEach(x=>x.addEventListener('change',update));update();
function render(){controls.update();renderer.render(scene,camera);requestAnimationFrame(render)}render();new ResizeObserver(()=>{const w=viewer.clientWidth,h=viewer.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}).observe(viewer);
$('form').addEventListener('submit',async e=>{e.preventDefault();const settings=`【Hanger Customize】\nText: ${text.value.slice(0,10)}\nFont Size: ${size.value}\nWidth: ${width.value} mm\nBody Color: ${body.value}\nText Color: ${ink.value}`;result.value=settings;result.style.display='block';try{await navigator.clipboard.writeText(settings);notice.textContent='設定をコピーしました。'}catch{result.select();notice.textContent='設定欄を選択しました。コピーしてください。'}});
